### ISSUE TITLE
No Usage examples

### ISSUE THREAD

**Issue by sjustfly** [ffried/GCDOperations#98]
It would be great if there were usage examples

**Comment by ffried** [comment]
The basic usage is described in the [PSOperations](https://github.com/pluralsight/PSOperations) repository as well as in the [Advanced Operations](https://developer.apple.com/videos/play/wwdc2015/226) WWDC video.
Given that this framework is mostly meant for non-Darwin platforms, all the Darwin-frameworks operations (like HealthKit, CloudKit, ...) aren't included.

**Comment by ffried** [comment]
Btw. in today's world, I'd recommend using async/await in Swift instead whenever possible
